"""
Analytics Reports model
"""
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, JSON, Integer, Text, Date
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import uuid
from app.db.base import Base


class AnalyticsReport(Base):
    __tablename__ = "analytics_reports"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True)
    execution_id = Column(UUID(as_uuid=True), ForeignKey("agent_executions.id"), nullable=True, index=True)
    
    # Report details
    report_type = Column(String(50), nullable=False)  # weekly, monthly, campaign_specific, custom
    title = Column(String(255), nullable=False)
    
    # Date range
    start_date = Column(Date, nullable=True)
    end_date = Column(Date, nullable=True)
    
    # Data sources
    data_sources = Column(JSON, nullable=False)  # Platforms analyzed
    
    # Report content
    summary = Column(Text, nullable=True)
    insights = Column(JSON, nullable=True)  # AI-generated insights
    recommendations = Column(JSON, nullable=True)  # AI recommendations
    metrics = Column(JSON, nullable=True)  # Key metrics
    
    # File
    report_file_key = Column(String(500), nullable=True)  # PDF/Excel file in storage
    
    # Status
    status = Column(String(50), default="generating")  # generating, completed, failed
    
    # Generated by
    generated_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    tenant = relationship("Tenant", backref="analytics_reports")
    execution = relationship("AgentExecution", backref="analytics_reports")
    
    def __repr__(self):
        return f"<AnalyticsReport(id={self.id}, type={self.report_type}, title={self.title})>"

