"""add_scheduled_posts_table

Revision ID: 0627fbe889eb
Revises: 5e92c08a7daa
Create Date: 2025-11-17 15:06:42.999462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0627fbe889eb'
down_revision: Union[str, None] = '5e92c08a7daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('include_images', sa.Boolean(), nullable=True),
    sa.Column('include_video', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_assistant_id'), 'scheduled_posts', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_capability_id'), 'scheduled_posts', ['capability_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_is_active'), 'scheduled_posts', ['is_active'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_next_run_at'), 'scheduled_posts', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_tenant_id'), 'scheduled_posts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_tenant_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_next_run_at'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_is_active'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_capability_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_assistant_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    # ### end Alembic commands ###
