"""add_website_url_to_tenant

Revision ID: c644bc56d27b
Revises: d86a44eb49e4
Create Date: 2025-11-10 01:30:40.839700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c644bc56d27b'
down_revision: Union[str, None] = 'd86a44eb49e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website_url')
    # ### end Alembic commands ###
